Backend game one-to-one
five-ducks/heron pull request #29
Opened 2024-10-13 15:49 UTC by SuperStarKang

## docker 수정
- 백엔드 컨테이너 이름 변경: django -> backend
- network 설정

## Websocket Setting
- websocket 디렉토리에 websocket 설정
- games 디렉토리에 게임 구현

## 1:1 게임 구현
1. 프론트에서 websocket 연결 요청
2. 백엔드에서 수락
3. 대기방이 있으면 해당 대기방으로 연결 (대기방 없으면 새로운 방 생성)
4. 2명 연결 시 게임 시작
5. 한 명이 5점 득점 시 종료
6. 종료 후 데이터베이스에 결과 저장

- 만약 중간에 새로고침이나 뒤로 가기를 누를 경우, websocket 연결 끊기

## Refactoring & Tournament
- refactoring은 tournament 구현 후 진행 예정
- tournament는 시험 끝난 후 구현할 예정

2024-10-14 13:23 UTC, leesiha requested changes
웹소켓 구현 부분의 py 파일은 검토하지 않았습니다. 
- `backend/games/consumers.py`
- `backend/games/group_manager.py`

검토가 필요하시다면 : 해당 파일에 대한 설명을 추가해주세요.

2024-10-14 13:23 UTC, leesiha commented on frontend/src/game/game.js
> +	handlePageLeave() {
handlePageLeave 랑 handleBeforeUnload 코드가 동일합니다

2024-10-14 13:23 UTC, leesiha commented on frontend/src/game/game.js
> +		let movement = null;
제안
```javascript
const movement = this.getMovementFromKeyPress(e);
``` 
```javascript
getMovementFromKeyPress(e) {
        const isPlayer1 = this.playerNumber === 1;
        const isPlayer2 = this.playerNumber === 2;
        if ((isPlayer1 || isPlayer2) && (e.key === 'ArrowUp' || e.key === 'ArrowDown')) {
            return { direction: e.key === 'ArrowUp' ? 'up' : 'down', player: this.playerNumber };
        }
        return null;
    }
```

2024-10-15 04:37 UTC, nuyheat commented on nginx/nginx.conf
> +			proxy_set_header X-Forwarded-Proto $scheme;
각 proxy_set_header 가 어떤 이유로 추가 되었는지 잘 모르겠습니다
이유에 대해 간단하게 주석 달아주시면 좋을 듯 합니다

2024-10-15 06:56 UTC, sunsetfactory approved these changes

2024-10-15 06:56 UTC, sunsetfactory commented on frontend/src/game/game.js
> +}
ㄴ..너무 길고 보기 힘듭니다.

2024-10-31 08:51 UTC, SuperStarKang commented on backend/config/settings.py
> +ALLOWED_HOSTS = ["*"]
설정바꾸기 귀찮아서 그냥 다 받는다고 설정했습니다.

2024-11-04 16:51 UTC, SuperStarKang commented
코드 업데이트 해서 다시 pr 올렸습니다.

2024-11-04 16:51 UTC, closed without merging