Frontend friend api
five-ducks/heron pull request #31
Opened 2024-10-17 05:48 UTC by sunsetfactory

<img width="442" alt="Screen Shot 2024-10-17 at 2 41 02 PM" src="https://github.com/user-attachments/assets/3ad264ac-1730-4142-9742-117cd860ecaf">
친구 추가 창 api추가 되었습니다.

<img width="442" alt="Screen Shot 2024-10-17 at 2 42 50 PM" src="https://github.com/user-attachments/assets/ff2489cf-3c43-4dc2-bf10-3e1ffe01c876">
친구 정보창 api수정되었습니다.

레이아웃 수정 전 파일 명 개선이 있었습니다.
<img width="89" alt="Screen Shot 2024-10-17 at 2 44 55 PM" src="https://github.com/user-attachments/assets/5c5b21b9-aa2d-4002-8596-daccbc4510b8">
avatar.js

<img width="192" alt="Screen Shot 2024-10-17 at 2 45 07 PM" src="https://github.com/user-attachments/assets/35f4da26-9ed7-4630-a8af-d07ac78f35cc">
profile.js

추가적으로 api요청 수정사항 issue에 올립니다.

2024-10-17 07:02 UTC, mingkyeongg commented on frontend/src/components/FriendGameRecords/FriendOutcome.js
> +		const img = new Avatar(0, 'm');
현재 이미지는 임시인가요??

2024-10-17 07:02 UTC, mingkyeongg commented on frontend/src/components/FriendSearchModal/FriendSearchModal.css
>      color: #333;
색상도 css변수에 추가해주시면 좋을 것 같습니다!

2024-10-17 07:03 UTC, mingkyeongg commented on frontend/src/components/FriendSearchModal/FriendSearchModal.css
> +    font-size: clamp(1.5rem, 4vw, 2rem);
요건 사이즈를 어떻게 쓰는 방식인지 궁금합니다~!

2024-10-17 07:05 UTC, mingkyeongg commented on frontend/src/components/FriendSearchModal/FriendSearchModal.css
>      background-color: #45a049;
기존 버튼 컴포넌트는 사용하지 않는건가요?

2024-10-17 07:07 UTC, mingkyeongg commented on frontend/src/components/FriendSearchModal/FriendSearchResult.js
div를 새로 만드는 이유가 있을까요??

2024-10-17 07:11 UTC, mingkyeongg commented on frontend/src/components/InfoFriendModal/InfoFriendModal.js
> +        gameRecords.render(this.userinfo.matches, this.userinfo.username, this.userinfo.profile_img);//
gameRecords 컴포넌트에서 render()가 자동으로 호출되고 있는데 한 번 더 사용한 것 같습니다!

2024-10-17 07:14 UTC, mingkyeongg commented on frontend/src/components/Profile/Avatar.js
> +        this.el.appendChild(frame);
Avatar 안에 frame이 필요한 이유가 있을까요?

2024-10-17 07:19 UTC, sunsetfactory commented on frontend/src/components/FriendGameRecords/FriendOutcome.js
> +		const img = new Avatar(0, 'm');
아직 userimg를 전달받지 못하고 있습니다. api수정되는데로 삽입할 예정입니다.

2024-10-17 07:22 UTC, sunsetfactory commented on frontend/src/components/FriendSearchModal/FriendSearchModal.css
>      background-color: #45a049;
이부분은 input button이 수정되는걸 확인하고 변경할 것 같습니다.
저도 마지막까지 임시로라도 컴포넌트를 가져다 쓸까 고민했네요

2024-10-17 07:23 UTC, sunsetfactory commented on frontend/src/components/FriendSearchModal/FriendSearchModal.css
> +    font-size: clamp(1.5rem, 4vw, 2rem);
인자 3개가 최소값 중간값 최대값을 의미하며
4vw로 작동하지만 최소 1.5rem 최대 2rem을 유지하게끔 사용됩니다.

2024-10-17 07:26 UTC, mingkyeongg commented on frontend/src/components/Sidebar/Sidebar.js
>          this.el.innerHTML = /*html*/`
생성자에서 className을 정해주면 좋을 것 같습니다!

2024-10-17 07:29 UTC, mingkyeongg reviewed
현재 렌더링 할 때 className을 지정하는 부분이 있는데
생성자 부모 컴포넌트 props로 tagName, className을 지정해 줄 수 있습니다! 활용해보시면 좋을 것 같습니다 ㅎㅎ

2024-10-17 07:29 UTC, sunsetfactory commented on frontend/src/components/FriendSearchModal/FriendSearchResult.js
results를 만들려고 했던 것 같은데 사용되지않고있네요 지워도 될 것 같습니다!

2024-10-18 06:54 UTC, leesiha commented on frontend/src/components/FriendSearchModal/FriendSearchModal.css
>      background-color: #45a049;
이 브랜치 합쳐지면 바로 main에서 branch 파서 PR 올리겠습니다!

2024-10-31 11:42 UTC, mingkyeongg commented on frontend/src/components/GameRecords/Outcome.js
> +		profilecontainer.appendChild(img.el);
이미 Profile이 컨테이너로 정의 되어 있는데 또 감싸준 이유가 있을까요?!

2024-10-31 11:59 UTC, leesiha requested changes
global.css 참고하여 font-family, font-size 통일해주세요.

2024-10-31 11:59 UTC, leesiha commented on frontend/src/components/FriendGameRecords/FriendOutcome.css
> +  font-size: 1.875rem; /* 30px를 rem 단위로 변경 */
font size는 global.css를 활용해주세요. 
1.875rem을 사용하고 싶으시다면 global.css에 추가하여 변수를 언급해주세요!
```suggestion
  font-size: var(--base-font-size);
```

2024-10-31 11:59 UTC, leesiha commented on frontend/src/components/FriendGameRecords/FriendOutcome.css
> +  font-family: 'DungGeunMo';
이것도 global.css에 있습니다.

2024-10-31 11:59 UTC, leesiha commented on frontend/src/components/FriendGameRecords/FriendOutcome.css
> +    font-size: 1.25rem;
```suggestion
    font-size: var(--base-font-size);
```

2024-10-31 11:59 UTC, leesiha commented on frontend/src/components/FriendSearchModal/FriendSearchModal.css
> +  font-size: clamp(18px, 5vw, 40px);
vw로 설정하시고 max-height 로 제한 걸어두면 자동으로 크기 조정이 되지 않나요?

2024-10-31 12:44 UTC, leesiha approved these changes

2024-11-04 07:16 UTC, mingkyeongg approved these changes

2024-11-04 07:17 UTC, merged